### ISSUE TITLE
Fails if TMPDIR environment variable not set

### ISSUE THREAD

**Issue by jetzerb** [eth-p/best#4]
I tried to install your `bat-extras` in a [Ubuntu 20.04 docker container](https://hub.docker.com/_/ubuntu?tab=tags&page=1&name=20.04), and it failed during the verification step with a bunch of error messages like this:
```
/home/jetzerb/tmp/install/bat-extras/.test-framework/libexec/best-runner.sh: line 173: /96419.async_96445.report: Permission denied
/home/jetzerb/tmp/install/bat-extras/.test-framework/libexec/best-runner.sh: line 63: /96419.test_version.stdout: Permission denied
mv: cannot stat '/96419.async_96445.report': No such file or directory
```

Turns out the `TMPDIR` environment variable isn't set.  After setting the variable to a suitable tmp dir, I tried again and everything ran to completion as expected.

FYI: I also have a [Manjaro](https://manjaro.org/) system that doesn't set TMPDIR by default, so perhaps it's not a very reliable variable?

Could you update to check whether `TMPDIR` is set, and if not then set it to a suitable value, such as one of the following:
- a newly-created dir within `$__BEST_ROOT`
- the output of `mktemp -d`
- /var/tmp
- /tmp

thanks.

**Comment by eth-p** [comment]
Thanks for letting me know! I just pushed a quick fix that appears to work when I manually `unset TMPDIR`, can you let me know if it solves the issue for you as well?

**Comment by jetzerb** [comment]
Yes, that fixed the problem!

It doesn't remove the tmp directory though...Here's output from the build inside a fresh Ubuntu 20.04 container:
```
root@1fa17b314c88:/usr/local/src/bat-extras# ls -l /tmp
total 0
```
```
root@1fa17b314c88:/usr/local/src/bat-extras# ./build.sh
This will not install the script.
Use --install for a global install.

Warning: cannot find shfmt. Unable to minify scripts.
Preparing scripts...
Building scripts...
. . . snip . . . 
Verifying scripts...
Submodule 'best' (https://github.com/eth-p/best.git) registered for path '.test-framework'
Cloning into '/usr/local/src/bat-extras/.test-framework'...
One or more tests were skipped.
Run ./test.sh for more detailed information.
Verified successfully.
```
```
root@1fa17b314c88:/usr/local/src/bat-extras# ls -l /tmp
total 4
drwx------ 2 root root 4096 May  1 12:52 tmp.reaL99NcYf
root@1fa17b314c88:/usr/local/src/bat-extras# ls -l /tmp/tmp.reaL99NcYf/
total 0
```

If either `TEST_ENV_TMPDIR` or `TMPDIR` environment variables are set, you should not remove the directory during cleanup.  But if you make your own temp dir, then you should remove it.

You could define a `TMPSUFFIX` variable (set to "BestTest" or similar), then `mktemp -d --suffix $TMPSUFFIX`, and then at the end of the script, remove `$TEST_ENV_TMPDIR` if it ends in `$TMPSUFFIX`.

**Comment by eth-p** [comment]
That is a bit of a problem. I'm going to have to do a more involved fix, it seems.

**Comment by eth-p** [comment]
~~I thought about it for a little while, and I don't really know if there's any real way to fix this aside from just setting the TMPDIR to `/tmp` instead of using `mktemp -d`.~~

~~The way that I designed `best`'s porcelain API was to output paths to files that capture the stdout/stderr of each of the tests, and I can't delete the temp directory with those files inside it when `best` exits. There's no way to know when the program reading the output has read the tempfiles, unfortunately...~~

~~Between the choices of hardcoding `/tmp` and leaving empty directories in `/tmp/...`, which do you think would be the more appropriate option? I'm leaning towards hardcoding it, since it's fairly reasonable to assume that any POSIX-compliant OS has a `/tmp` directory.~~

Nevermind. It turns out I never implemented `--VERBOSE` for `--porcelain` mode, so it should be doable. I'll just have to figure out another way to print the output that doesn't rely on tempfiles. It should all be fixed with https://github.com/eth-p/best/commit/c4e11860e9eefe37e6478fcbc286fe76202e7703, which can be tested in the current `bat-extras` master branch.

**Comment by jetzerb** [comment]
Looks good!
- Successful build with and without `TMPDIR` set
- No leftover tmp dir
